name: Ejecutar Script al hacer Push en Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Git
        env:
          # Configura estas variables de entorno con los valores correspondientes
          # de tus secretos de GitHub
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --local user.name "${GIT_USER_NAME}"
          git config --local user.email "${GIT_USER_EMAIL}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.password "${GITHUB_TOKEN}"
          git checkout master
          git branch -D gh-pages
          git push origin --delete gh-pages
          git checkout -b gh-pages
          git rm -r .
          git clean -fxd
          git add dist
          git commit -m "Actualizar rama gh-pages con contenido de la carpeta dist con Github Actions"
          git push origin gh-pages
