name: Ejecutar Script al hacer Push en Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Git
        env:
          # Configura estas variables de entorno con los valores correspondientes
          # de tus secretos de GitHub
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          set -x
          git config --local user.name "${GIT_USER_NAME}"
          git config --local user.email "${GIT_USER_EMAIL}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"
          echo "El token es: ${GITHUB_TOKEN}"
          echo "El usuario es: ${GIT_USER_NAME}"
          echo "El email es: ${GIT_USER_EMAIL}"
          git config --global user.password "${GITHUB_TOKEN}"
          git push origin -d gh-pages
          git add dist -f
          git commit -m "deleted gh-pages branch by Github Actions"
          git subtree push --prefix dist origin gh-pages
          set +x
