name: Update gh-pages

on:
  push:
    branches:
      - master

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Switch to gh-pages branch
        run: git checkout gh-pages

      - name: Clean gh-pages branch
        run: |
          git rm -rf .
          git clean -fxd

      - name: Copy dist folder to gh-pages branch
        run: |
          cp -r dist/* .

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update gh-pages with dist folder"
          git push origin gh-pages
