name: Ejecutar Script al hacer Push en Master

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ejecutar Script
        run: |
          chmod +x predeploy.sh
          ./predeploy.sh
